### ISSUE TITLE
请问是否有QQ群的部署方法

### ISSUE THREAD

**Issue by LSGLSH** [Valorant-Shop-CN/QQ-Valorant-Bot#1]
因为本人手机使用的tim，没有QQ频道，只能在QQ群查询，本人有一台本地服务器，可以搭建在直接服务器进行查询详细，可以的话留个联系方式QQ2368343278

**Comment by musnows** [comment]
> 因为本人手机使用的tim，没有QQ频道，只能在QQ群查询，本人有一台本地服务器，可以搭建在直接服务器进行查询详细，可以的话留个联系方式QQ2368343278

参考 [kook-valorant-bot](https://github.com/Valorant-Shop-CN/Kook-Valorant-Bot) 中的docs/api，直接调用api查询，这样可以直接在任何设备使用浏览器查询到商店结果

qq群机器人的框架很容易被封，目前没有上线qq群机器人的计划
